### ISSUE TITLE
Should support single plugin files within plugins folder

### ISSUE THREAD

**Issue by glueckpress** [Rarst/update-blocker#1]
Currently, blocking only works when the to-be-blocked plugin resides in a subfolder of plugins dir, like `foo-plugin/foo-plugin.php`. Plugins consisting of just 1 file inside of plugins dir are not supported.

**Comment by Rarst** [comment]
I am testing out the case and it _does_ work. Have to provide name as just `foo-plugin.php` (no parent directory).

Has that failed for you? Could you show code of your filter in full?

**Comment by glueckpress** [comment]
Apologies for being out of touch for soooo long. I’ve looked into this again and don’t seem to be able to reproduce it anymore. Please feel free to close this issue.
